default_platform(:ios)

platform :ios do

  desc "Sync certificates and provisioning profiles"
  lane :sync_signing do
    match(type: "appstore", readonly: true)
  end

  desc "Upload to TestFlight (Internal)"
  lane :beta_internal do
    pilot(
      distribute_external: false,
      notify_external_testers: false
    )
  end

  desc "Upload to TestFlight (External Beta)"
  lane :beta_external do
    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["External Beta"]
    )
  end

  desc "Submit to App Store"
  lane :release do
    deliver(
      submit_for_review: true,
      phased_release: true,
      automatic_release: false,
      skip_binary_upload: true
    )
  end

end
